codecov:
  token: "8af82b32-850e-49a6-82c0-6ffe11a5de9d"
  bot: "codecov-io"
  ci:
    - "https://travis-ci.com/github/Allen0929/TravisCITest"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes